const WORLD_LOCATION_SUGGESTIONS = [
  'Milano, Italy',
  'Milan, Italy',
  'Roma, Italy',
  'Rome, Italy',
  'Torino, Italy',
  'Turin, Italy',
  'Firenze, Italy',
  'Florence, Italy',
  'Venezia, Italy',
  'Venice, Italy',
  'Verona, Italy',
  'Bologna, Italy',
  'Napoli, Italy',
  'Naples, Italy',
  'Palermo, Italy',
  'Genova, Italy',
  'Genoa, Italy',
  'Parma, Italy',
  'Modena, Italy',
  'Brescia, Italy',
  'Bergamo, Italy',
  'Treviso, Italy',
  'Padova, Italy',
  'Trieste, Italy',
  'Barolo, Italy',
  'Alba, Italy',
  'Montalcino, Italy',
  'Montepulciano, Italy',
  'Bolgheri, Italy',
  'Paris, France',
  'Bordeaux, France',
  'Lyon, France',
  'Marseille, France',
  'Nice, France',
  'Dijon, France',
  'Beaune, France',
  'Reims, France',
  'Strasbourg, France',
  'London, United Kingdom',
  'Manchester, United Kingdom',
  'Edinburgh, United Kingdom',
  'Dublin, Ireland',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Valencia, Spain',
  'Seville, Spain',
  'Bilbao, Spain',
  'Lisbon, Portugal',
  'Porto, Portugal',
  'Berlin, Germany',
  'Munich, Germany',
  'Hamburg, Germany',
  'Frankfurt, Germany',
  'Cologne, Germany',
  'Vienna, Austria',
  'Zurich, Switzerland',
  'Geneva, Switzerland',
  'Basel, Switzerland',
  'Amsterdam, Netherlands',
  'Rotterdam, Netherlands',
  'Brussels, Belgium',
  'Copenhagen, Denmark',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Helsinki, Finland',
  'Athens, Greece',
  'Istanbul, Turkey',
  'New York, NY, United States',
  'Brooklyn, NY, United States',
  'Los Angeles, CA, United States',
  'San Francisco, CA, United States',
  'Napa, CA, United States',
  'Sonoma, CA, United States',
  'Chicago, IL, United States',
  'Miami, FL, United States',
  'Las Vegas, NV, United States',
  'Austin, TX, United States',
  'Dallas, TX, United States',
  'Houston, TX, United States',
  'Seattle, WA, United States',
  'Portland, OR, United States',
  'Boston, MA, United States',
  'Washington, DC, United States',
  'Philadelphia, PA, United States',
  'Atlanta, GA, United States',
  'Denver, CO, United States',
  'Phoenix, AZ, United States',
  'San Diego, CA, United States',
  'Toronto, Canada',
  'Montreal, Canada',
  'Vancouver, Canada',
  'Calgary, Canada',
  'Mexico City, Mexico',
  'Guadalajara, Mexico',
  'Cancun, Mexico',
  'Buenos Aires, Argentina',
  'Mendoza, Argentina',
  'Santiago, Chile',
  'Lima, Peru',
  'Bogota, Colombia',
  'Sao Paulo, Brazil',
  'Rio de Janeiro, Brazil',
  'Cape Town, South Africa',
  'Johannesburg, South Africa',
  'Dubai, United Arab Emirates',
  'Abu Dhabi, United Arab Emirates',
  'Doha, Qatar',
  'Riyadh, Saudi Arabia',
  'Tel Aviv, Israel',
  'Singapore, Singapore',
  'Hong Kong, Hong Kong',
  'Tokyo, Japan',
  'Kyoto, Japan',
  'Osaka, Japan',
  'Seoul, South Korea',
  'Shanghai, China',
  'Beijing, China',
  'Taipei, Taiwan',
  'Bangkok, Thailand',
  'Ho Chi Minh City, Vietnam',
  'Hanoi, Vietnam',
  'Kuala Lumpur, Malaysia',
  'Jakarta, Indonesia',
  'Manila, Philippines',
  'Mumbai, India',
  'Delhi, India',
  'Bengaluru, India',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Perth, Australia',
  'Auckland, New Zealand',
  'Wellington, New Zealand',
];

function normalizeLocation(value: string): string {
  return value.trim().replace(/\s+/g, ' ');
}

export function buildLocationSuggestions(existingLocations: string[], limit = 800): string[] {
  const seen = new Set<string>();
  const suggestions: string[] = [];

  for (const rawLocation of [...WORLD_LOCATION_SUGGESTIONS, ...existingLocations]) {
    const location = normalizeLocation(rawLocation);
    const key = location.toLocaleLowerCase();

    if (!location || key === 'no data' || seen.has(key)) {
      continue;
    }

    seen.add(key);
    suggestions.push(location);

    if (suggestions.length >= limit) {
      break;
    }
  }

  return suggestions;
}
